-- ================================================================
-- SQL DML TEMPLATE (TOPIC 09)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) INSERT scripts for all required tables in your database.
-- 2) At least 10 records per table with meaningful, realistic values.
-- 3) UPDATE / DELETE scripts where they are relevant to business logic.
-- 4) If UPDATE / DELETE are not relevant for a table, add a short note
--    in documentation explaining why.
-- 5) Comments by section so the script is easy to read and run.
--
-- SCRIPT GOALS:
-- - Populate the database with usable test data.
-- - Validate constraints through realistic DML scenarios.
-- - Support the core functionality of your application.
--
-- RECOMMENDED ORDER:
-- 1) Reference data (lookups/dictionaries)
-- 2) Core entities
-- 3) Transactional data
-- 4) Optional UPDATE / DELETE checks
--
-- IMPORTANT:
-- - Use anonymized or privacy-safe sample data where possible.
-- - The script must execute in PostgreSQL.
-- - Submit this as one SQL file.
-- ================================================================

-- Add your DML below this line
-- Stores available gym membership plans, including type, duration, and pricing
CREATE TABLE Memberships (
  membership_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_type VARCHAR(50) NOT NULL,
  start_date DATE,
  end_date DATE,
  price DECIMAL(10, 2) NOT NULL CHECK (price >= 0)
);

-- Stores information about gym members and links them to membership plans
CREATE TABLE Members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(30) UNIQUE,
  date_of_birth DATE,
  membership_id INTEGER REFERENCES Memberships(membership_id)
);

-- Stores trainer personal and contact information
CREATE TABLE Trainers (
  trainer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20),
  email VARCHAR(100) UNIQUE
);

-- Stores information about available fitness classes and their assigned main trainer
CREATE TABLE Classes (
  class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name VARCHAR(100) NOT NULL,
  room_number INT,
  trainer_id INT,
  FOREIGN KEY(trainer_id) REFERENCES Trainers(trainer_id)
);

-- Stores the schedule of fitness classes, including start and end times
CREATE TABLE ClassSchedule (
  class_schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INT NOT NULL,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  FOREIGN KEY(class_id) REFERENCES Classes(class_id)
);

-- Tracks member attendance for scheduled classes, including private sessions
CREATE TABLE Attendance (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT NOT NULL,
  class_schedule_id INT NOT NULL,
  activity_start_time TIMESTAMP,
  activity_end_time TIMESTAMP,
  is_private_class BOOLEAN DEFAULT FALSE,
  FOREIGN KEY(member_id) REFERENCES Members(member_id),
  FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);

-- Stores gym equipment inventory and current availability status
CREATE TABLE Equipment (
  equipment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name VARCHAR(255) NOT NULL,
  equipment_status VARCHAR(255),
  quantity INT CHECK (quantity >= 0)
);

-- Tracks equipment usage and return status for specific class session
CREATE TABLE EquipmentClasses (
  equipment_id INT NOT NULL,
  class_schedule_id INT NOT NULL,
  is_returned BOOLEAN,
  PRIMARY KEY(equipment_id, class_schedule_id),
  FOREIGN KEY(equipment_id) REFERENCES Equipment(equipment_id),
  FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);

-- Stores members' fitness progress measurements over time
CREATE TABLE Progress (
  progress_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT NOT NULL,
  check_in_date DATE DEFAULT CURRENT_DATE,
  weight_kg NUMERIC(5, 2) NOT NULL CHECK (weight_kg > 0),
  height_cm NUMERIC(5, 2) CHECK (height_cm > 0),
  body_fat_percentage NUMERIC(4, 2) CHECK (body_fat_percentage BETWEEN 0 AND 100),
  muscle_mass_kg NUMERIC(5, 2) CHECK (muscle_mass_kg >= 0),
  notes TEXT,
  FOREIGN KEY(member_id) REFERENCES Members(member_id)
);

-- Links trainers to scheduled classes with optional role descriptions
CREATE TABLE ClassTrainers (
  trainer_id INT NOT NULL,
  class_schedule_id INT NOT NULL,
  role_description VARCHAR(255),
  PRIMARY KEY(trainer_id, class_schedule_id),
  FOREIGN KEY(trainer_id) REFERENCES Trainers(trainer_id),
  FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);

-- Defines equipment required for specific scheduled classes
CREATE TABLE ClassEquipment (
  equipment_id INT NOT NULL,
  class_schedule_id INT NOT NULL,
  quantity_required INT DEFAULT 1,
  PRIMARY KEY(equipment_id, class_schedule_id),
  FOREIGN KEY(equipment_id) REFERENCES Equipment(equipment_id),
  FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);

-- Stores trainer professional specializations and expertise areas
CREATE TABLE TrainersSpecializations (
  specialization_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id INT REFERENCES Trainers(trainer_id),
  specialization_name VARCHAR(30) NOT NULL
);

-- Stores members' fitness goals, deadlines, and achievement status
CREATE TABLE FitnessGoals (
  goal_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT REFERENCES Members(member_id),
  goal_description VARCHAR(100),
  target_date DATE,
  achievement_date DATE,
  is_achieved BOOLEAN DEFAULT FALSE
);

-- Stores personal training sessions booked between members and trainers
CREATE TABLE PersonalTraining (
  training_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INT REFERENCES Members(member_id),
  trainer_id INT REFERENCES Trainers(trainer_id),
  training_date TIMESTAMP NOT NULL,
  duration_minutes INT CHECK (duration_minutes > 0)
);

-- Add membership records
INSERT INTO Memberships (membership_id, membership_type, start_date, end_date, price)
VALUES
(0, 'Single use', '2026-01-12', '2026-02-12', 200.00),
(1, 'Single use', '2026-01-12', '2026-01-12', 200.00),
(2, 'Monthly', '2026-02-01', '2026-03-01', 500.00),
(3, 'Monthly Plus', '2026-03-05', '2026-04-05', 650.00),
(4, 'Yearly', '2026-04-01', '2027-04-01', 4800.00),
(5, 'Premium Yearly', '2026-05-10', '2027-05-10', 7200.00),
(6, 'Student Monthly', '2026-06-15', '2026-07-15', 350.00),
(7, 'Family Monthly', '2026-07-20', '2026-08-20', 900.00),
(8, 'Weekend Pass', '2026-08-01', '2026-08-31', 300.00),
(9, 'Personal Training Package', '2026-09-07', '2026-11-07', 1500.00),
(10, 'Corporate Membership', '2026-10-01', '2027-01-01', 2500.00);

-- Update members email column to store longer email addresses
ALTER TABLE Members
ALTER COLUMN email TYPE VARCHAR(100);

-- Add member records
INSERT INTO Members (member_id, full_name, phone, email, date_of_birth, membership_id)
VALUES
(21, 'Ivan Petrenko', '+380501112233', 'ivan.petrenko@example.com', '1995-04-12', 1),
(22, 'Olena Shevchenko', '+380672223344', 'olena.shevchenko@example.com', '1998-09-25', 2),
(23, 'Andrii Kovalenko', '+380933334455', 'andrii.kovalenko@example.com', '1990-01-17', 3),
(24, 'Maksym Bondarenko', '+380504445566', 'maksym.bondarenko@example.com', '1992-06-03', 1),
(25, 'Sofia Melnyk', '+380675556677', 'sofia.melnyk@example.com', '2000-11-08', 2),
(26, 'Dmytro Tkachenko', '+380936667788', 'dmytro.tkachenko@example.com', '1988-02-21', 3),
(27, 'Anastasiia Moroz', '+380507778899', 'anastasiia.moroz@example.com', '1997-07-14', 1),
(28, 'Yurii Kravchenko', '+380678889900', 'yurii.kravchenko@example.com', '1994-12-30', 2),
(29, 'Kateryna Savchenko', '+380939990011', 'kateryna.savchenko@example.com', '1999-03-05', 3),
(30, 'Vladyslav Polishchuk', '+380501010101', 'vladyslav.polishchuk@example.com', '1991-08-19', 1),
(31, 'Iryna Lysenko', '+380672020202', 'iryna.lysenko@example.com', '1996-10-27', 2),
(32, 'Bohdan Hrytsenko', '+380933030303', 'bohdan.hrytsenko@example.com', '1989-05-11', 3),
(33, 'Natalia Romanenko', '+380504040404', 'natalia.romanenko@example.com', '1993-01-29', 1),
(34, 'Oleksandr Marchenko', '+380675050505', 'oleksandr.marchenko@example.com', '1987-09-16', 2),
(35, 'Viktoriia Koval', '+380936060606', 'viktoriia.koval@example.com', '2001-04-02', 3),
(36, 'Taras Honchar', '+380507070707', 'taras.honchar@example.com', '1990-06-24', 1),
(37, 'Alina Sydorenko', '+380678080808', 'alina.sydorenko@example.com', '1998-12-09', 2),
(38, 'Roman Mazur', '+380939090909', 'roman.mazur@example.com', '1992-03-18', 3),
(39, 'Mariia Danyliuk', '+380501212121', 'mariia.danyliuk@example.com', '1995-07-07', 1),
(40, 'Serhii Pavlenko', '+380672323232', 'serhii.pavlenko@example.com', '1986-11-23', 2);

-- Trainers
INSERT INTO Trainers (trainer_id, first_name, last_name, phone_number, email)
VALUES
(1, 'Taras', 'Petrenko', '+380671411881', 'taraspetrenko69@gmail.com'),
(2, 'Anna', 'Anonenco', '+380502281312', 'annaanonenco76@gmail.com'),
(3, 'Oleksandr', 'Voytenko', '+380732716033', 'oleksandrvoytenko67@gmail.com'),
(4, 'Stepan', 'Shevchenko', '+380995854489', 'stepanshevchenko42@gmail.com'),
(5, 'Dmytro', 'Bondarenko', '+380505555555', 'dmytrobondarenko51@gmail.com'),
(6, 'Olena', 'Tkachenko', '+380996661889', 'olenatkachenko79@gmail.com'),
(7, 'Maksym', 'Zilberman', '+380777777777', 'maksymzilberman99@gmail.com'),
(8, 'Kateryna', 'Genadievna', '+380678515162', 'katerynagenadievna88@gmail.com'),
(9, 'Arsen', 'Markan', '+380778619784', 'arsenmarkan68@gmail.com'),
(10, 'Oleksii', 'Levkin', '+380672711589', 'oleksiilevkin24@gmail.com'),
(11, 'Andrii', 'Kovalenko', '+380501112233', 'andrii.k@example.com'),
(12, 'Olena', 'Shevchenko', '+380672223344', 'olena.s@example.com'),
(13, 'Maksym', 'Bondarenko', '+380933334455', 'maksym.b@example.com'),
(14, 'Iryna', 'Lysenko', '+380504445566', 'iryna.l@example.com'),
(15, 'Dmytro', 'Tkachenko', '+380675556677', 'dmytro.t@example.com'),
(16, 'Sofia', 'Melnyk', '+380936667788', 'sofia.m@example.com'),
(17, 'Yurii', 'Kravchenko', '+380507778899', 'yurii.k@example.com'),
(18, 'Kateryna', 'Savchenko', '+380678889900', 'katya.s@example.com'),
(19, 'Vladyslav', 'Polishchuk', '+380939990011', 'vlad.p@example.com');

-- Classes
INSERT INTO Classes (class_id, class_name, room_number, trainer_id)
VALUES
(1, 'Yoga', 21, 1),
(2, 'CrossFit', 22, 2),
(3, 'Pilates', 23, 3),
(4, 'Boxing', 24, 4),
(5, 'Zumba', 25, 5),
(6, 'HIIT', 26, 6),
(7, 'Stretching', 27, 7),
(8, 'Strength Training', 28, 8),
(9, 'Functional Training', 29, 9),
(10, 'Cardio Blast', 30, 10),
(11, 'Yoga Flow', 1, 2),
(12, 'HIIT Blast', 2, 5),
(13, 'Strength & Power', 3, 1),
(14, 'Pilates Core', 1, 4),
(15, 'Cardio Kickboxing', 2, 6),
(16, 'Functional Fit', 3, 3);

-- Add scheduled class sessions
INSERT INTO ClassSchedule (class_schedule_id, class_id, start_time, end_time)
VALUES
(1, 1, '2026-06-02 08:00:00', '2026-06-02 09:00:00'),
(2, 2, '2026-06-02 10:00:00', '2026-06-02 11:00:00'),
(3, 3, '2026-06-03 09:00:00', '2026-06-03 10:30:00'),
(4, 4, '2026-06-03 11:00:00', '2026-06-03 12:00:00'),
(5, 5, '2026-06-04 17:00:00', '2026-06-04 18:00:00'),
(6, 6, '2026-06-05 07:30:00', '2026-06-05 08:30:00'),
(7, 7, '2026-06-06 08:00:00', '2026-06-06 09:00:00'),
(8, 8, '2026-06-06 10:00:00', '2026-06-06 11:00:00'),
(9, 9, '2026-06-07 12:00:00', '2026-06-07 13:00:00'),
(10, 10, '2026-06-07 14:00:00', '2026-06-07 15:00:00'),
(11, 11, '2026-06-02 08:00:00', '2026-06-02 09:00:00'),
(12, 12, '2026-06-02 10:00:00', '2026-06-02 11:00:00'),
(13, 13, '2026-06-03 09:00:00', '2026-06-03 10:30:00'),
(14, 14, '2026-06-03 11:00:00', '2026-06-03 12:00:00'),
(15, 15, '2026-06-04 17:00:00', '2026-06-04 18:00:00'),
(16, 16, '2026-06-05 07:30:00', '2026-06-05 08:30:00'),
(17, 11, '2026-06-06 08:00:00', '2026-06-06 09:00:00'),
(18, 12, '2026-06-06 10:00:00', '2026-06-06 11:00:00');

-- Add gym equipment records
INSERT INTO Equipment (equipment_id, equipment_name, equipment_status, quantity)
VALUES
(1, 'Yoga Mat', 'available', 20),
(2, 'Resistance Band', 'available', 30),
(3, 'Dumbbell 5kg', 'available', 15),
(4, 'Dumbbell 10kg', 'available', 10),
(5, 'Barbell', 'available', 8),
(6, 'Kettlebell 16kg', 'in use', 6),
(7, 'Foam Roller', 'available', 12),
(8, 'Boxing Gloves', 'available', 16),
(9, 'Jump Rope', 'available', 20),
(10, 'Pilates Ring', 'available', 10);

-- Tracks equipment usage and return status for specific class session
INSERT INTO EquipmentClasses (equipment_id, class_schedule_id, is_returned)
VALUES
(1, 11, TRUE),   -- Yoga Mat     → Yoga Flow (06-02)
(7, 11, TRUE),   -- Foam Roller  → Yoga Flow (06-02)
(2, 12, TRUE),   -- Resist.Band  → HIIT Blast (06-02)
(9, 12, TRUE),   -- Jump Rope    → HIIT Blast (06-02)
(3, 13, TRUE),   -- Dumbbell 5kg → Strength (06-03)
(4, 13, TRUE),   -- Dumbbell 10kg→ Strength (06-03)
(5, 13, FALSE),  -- Barbell      → Strength (06-03) — ще не повернуто
(1, 14, TRUE),   -- Yoga Mat     → Pilates (06-03)
(10, 14, TRUE),  -- Pilates Ring → Pilates (06-03)
(8, 15, TRUE),   -- Boxing Gloves→ Kickboxing (06-04)
(9, 15, TRUE),   -- Jump Rope    → Kickboxing (06-04)
(6, 16, FALSE),  -- Kettlebell   → Functional Fit (06-05) — ще не повернуто
(2, 16, TRUE),   -- Resist.Band  → Functional Fit (06-05)
(1, 17, TRUE),   -- Yoga Mat     → Yoga Flow (06-06)
(2, 18, TRUE);   -- Resist.Band  → HIIT Blast (06-06)

-- Attendance
INSERT INTO Attendance
(member_id, class_schedule_id, activity_start_time, activity_end_time, is_private_class)
VALUES
(21, 1, '2026-05-01 09:00:00', '2026-05-01 10:00:00', FALSE),
(22, 2, '2026-05-02 10:00:00', '2026-05-02 11:00:00', FALSE),
(23, 3, '2026-05-03 11:00:00', '2026-05-03 12:00:00', TRUE),
(24, 4, '2026-05-04 12:00:00', '2026-05-04 13:00:00', FALSE),
(25, 5, '2026-05-05 13:00:00', '2026-05-05 14:00:00', FALSE),
(26, 6, '2026-05-06 14:00:00', '2026-05-06 15:00:00', TRUE),
(27, 7, '2026-05-07 15:00:00', '2026-05-07 16:00:00', FALSE),
(28, 8, '2026-05-08 16:00:00', '2026-05-08 17:00:00', FALSE),
(29, 9, '2026-05-09 17:00:00', '2026-05-09 18:00:00', TRUE),
(30, 10, '2026-05-10 18:00:00', '2026-05-10 19:00:00', FALSE);

-- Add member progress records
INSERT INTO Progress (member_id, check_in_date, weight_kg, height_cm, body_fat_percentage, muscle_mass_kg, notes)
VALUES
(21, '2026-05-01', 82.5, 180, 18.5, 35.0, 'First measurement, goal: weight loss'),
(22, '2026-05-02', 65.0, 165, 22.0, 25.5, 'Start of training program'),
(25, '2026-05-05', 90.2, 185, 24.4, 38.1, 'Focus on cardio'),
(27, '2026-05-10', 55.5, 160, 19.0, 22.0, 'Good physical shape'),
(28, '2026-05-15', 105.0, 192, 28.0, 42.0, 'Powerlifting preparation'),
(31, '2026-06-01', 80.0, 180, 17.5, 35.5, 'Intermediate measurement: lost 2.5 kg'),
(34, '2026-06-02', 63.5, 165, 20.5, 26.0, 'Improvement in endurance'),
(36, '2026-06-03', 75.0, 175, 15.0, 36.5, 'Maintaining shape'),
(39, '2026-06-05', 68.0, 170, 25.0, 24.0, 'Rehabilitation after knee injury'),
(40, '2026-06-10', 88.0, 178, 16.0, 39.0, 'Bulking phase');

-- Links trainers to scheduled classes with optional role descriptions
INSERT INTO ClassTrainers (trainer_id, class_schedule_id, role_description)
VALUES
(1, 1, 'Lead Instructor'),
(2, 1, 'Assistant/Spotter'),
(3, 2, 'Main Coach'),
(4, 3, 'Lead Instructor'),
(5, 4, 'Choreographer'),
(6, 5, 'Main Coach'),
(1, 6, 'Guest Trainer'),
(7, 7, 'Lead Instructor'),
(8, 8, 'Rehabilitation Specialist'),
(9, 9, 'Pacer'),
(10, 10, 'Lead Instructor');

-- Defines equipment required for specific scheduled classes
INSERT INTO ClassEquipment (equipment_id, class_schedule_id, quantity_required)
VALUES
(1, 1, 15),
(2, 2, 20),
(3, 3, 10),
(4, 4, 15),
(1, 5, 12),
(5, 6, 5),
(6, 7, 10),
(7, 8, 8),
(8, 9, 15),
(9, 10, 2);

-- Побачила, що влучніше буде створити окрему таблицю зі спеціалізціями
CREATE TABLE specializations (
  specialization_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specialization_name VARCHAR(30)
);

-- Видалення старого формату таблиці TrainersSpecializations без видалення самої таблиці
ALTER TABLE TrainersSpecializations
DROP CONSTRAINT trainersspecializations_pkey;

ALTER TABLE TrainersSpecializations
DROP COLUMN specialization_name;

ALTER TABLE TrainersSpecializations
ALTER COLUMN specialization_id DROP IDENTITY IF EXISTS;

ALTER TABLE TrainersSpecializations
ALTER COLUMN specialization_id SET NOT NULL;

ALTER TABLE TrainersSpecializations
ALTER COLUMN trainer_id SET NOT NULL;

ALTER TABLE TrainersSpecializations
ADD CONSTRAINT fk_trainersspecializations_specialization
FOREIGN KEY (specialization_id) REFERENCES specializations(specialization_id);

-- Додала композитній первинній ключ до таблиці TrainersSpecializations
ALTER TABLE TrainersSpecializations
ADD CONSTRAINT pk_trainer_specialization
PRIMARY KEY (trainer_id, specialization_id);

--Додавання значень до таблиці specializations
INSERT INTO specializations (specialization_name)
VALUES
('Personal Training'),
('Weight Loss Coaching'),
('Bodybuilding'),
('Rehabilitation Training'),
('Functional Training'),
('HIIT Training'),
('Mobility & Flexibility');

--Оновлення данних у таблиці specializations
UPDATE specializations
SET specialization_name = 'Strength Training'
WHERE specialization_name = 'Personal Training';

--Додавання значень до таблиці trainersspecializations
INSERT INTO TrainersSpecializations (specialization_id, trainer_id)
VALUES
(1, 1),
(2, 9),
(3, 8),
(4, 7),
(5, 6),
(6, 5),
(7, 4),
(1, 3),
(2, 2),
(3, 1);

--Додавання значень до таблиці FitnessGoals
INSERT INTO FitnessGoals (member_id, goal_description, target_date, achievement_date, is_achieved)
VALUES
(21, 'Lose 3 kg body fat', '2026-07-01', NULL, FALSE),
(33, 'Run 5 km without stopping', '2026-06-15', '2026-06-10', TRUE),
(27, 'Increase squat to 120 kg', '2026-08-01', NULL, FALSE),
(40, 'Improve flexibility for splits', '2026-07-20', NULL, FALSE),
(22, 'Attend gym 3x per week for 2 months', '2026-05-30', '2026-05-28', TRUE),
(35, 'Bench press bodyweight', '2026-09-01', NULL, FALSE),
(29, 'Complete 30-day fitness challenge', '2026-06-30', '2026-06-25', TRUE),
(24, 'Reduce waist size by 5 cm', '2026-07-10', NULL, FALSE),
(38, 'Run 10 km race', '2026-10-01', NULL, FALSE),
(31, 'Master proper deadlift form', '2026-06-20', '2026-06-18', TRUE);

--Додавання значень до таблиці PersonalTraining
INSERT INTO PersonalTraining (member_id, trainer_id, training_date, duration_minutes)
VALUES
(21, 3, '2026-06-01 10:00:00', 60),
(34, 7, '2026-06-02 12:30:00', 45),
(28, 1, '2026-06-03 09:00:00', 90),
(40, 5, '2026-06-03 18:00:00', 60),
(22, 9, '2026-06-04 07:30:00', 50),
(31, 2, '2026-06-04 19:00:00', 75),
(27, 6, '2026-06-05 11:15:00', 60),
(36, 4, '2026-06-05 17:45:00', 45),
(25, 8, '2026-06-06 08:00:00', 60),
(39, 3, '2026-06-06 20:00:00', 90);

-- Create indexes to improve query performance
CREATE INDEX idx_members_membership_id ON Members(membership_id);
CREATE INDEX idx_attendance_member_id ON Attendance(member_id);
CREATE INDEX idx_attendance_schedule_id ON Attendance(class_schedule_id);
CREATE INDEX idx_progress_member_id ON Progress(member_id);
CREATE INDEX idx_personaltraining_member_id ON PersonalTraining(member_id);
CREATE INDEX idx_personaltraining_trainer_id ON PersonalTraining(trainer_id);
CREATE INDEX idx_classschedule_class_id ON ClassSchedule(class_id);
CREATE INDEX idx_trainerspecializations_trainer_id ON TrainersSpecializations(trainer_id);

