-- ================================================================
-- SQL DDL TEMPLATE (TOPIC 04)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) Full PostgreSQL DDL for your finalized schema.
-- 2) CREATE TABLE statements for all entities from your ER diagram.
-- 3) Primary keys, foreign keys, NOT NULL, UNIQUE, CHECK constraints.
-- 4) Indexes for important search/join columns.
-- 5) Clean structure and comments (group by tables/constraints/indexes).
--
-- RECOMMENDED ORDER:
-- 1) Tables
-- 2) Constraints (if not inline)
-- 3) Indexes
--
-- TEAM NOTE:
-- Add short attribution comments for who implemented which part.
-- Example:
-- [Name] - users, roles, permissions tables
-- [Name] - orders, payments, invoices tables
--
-- IMPORTANT:
-- The script must run in PostgreSQL and produce a working schema that
-- matches your approved ER diagram and conceptual schema.
-- Submit this as one SQL file.
-- ================================================================

-- Add your DDL below this line

-- Stores available gym membership plans, including type, duration, and pricing
CREATE TABLE Memberships (
  membership_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_type VARCHAR(50) NOT NULL,
  start_date DATE,
  end_date DATE,
  price DECIMAL(10, 2) not null check (price >= 0)
);
-- Stores information about gym members and links them to membership plans
CREATE TABLE Members (
  member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(30) unique,
  date_of_birth DATE,
  membership_id INTEGER REFERENCES Memberships(membership_id)
);
-- Stores trainer personal and contact information
CREATE TABLE Trainers (
  trainer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
phone_number VARCHAR(20),
email VARCHAR(100) unique
);
-- Stores information about available fitness classes and their assigned main trainer
CREATE TABLE Classes (
  class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name VARCHAR(100) NOT NULL, 
  room_number INT,
  trainer_id INT,
  FOREIGN KEY(trainer_id) REFERENCES Trainers(trainer_id)
);
-- Stores the schedule of fitness classes, including start and end times
CREATE TABLE ClassSchedule (
  class_schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INT NOT NULL,
  start_time timestamp,
  end_time timestamp,
  FOREIGN KEY(class_id) REFERENCES Classes(class_id)
);
-- Tracks member attendance for scheduled classes, including private sessions
CREATE TABLE Attendance(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
member_id INT NOT NULL,
class_schedule_id INT NOT NULL,
activity_start_time timestamp,
activity_end_time timestamp,
is_private_class BOOLEAN default false,
FOREIGN KEY(member_id) REFERENCES Members(member_id),
FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);
-- Stores gym equipment inventory and current availability status
CREATE TABLE Equipment (
  equipment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name VARCHAR(255) not null,
  equipment_status VARCHAR(255),
  quantity INT check (quantity >= 0)
);
-- Tracks equipment usage and return status for specific class session
CREATE TABLE EquipmentClasses (
  equipment_id INT NOT NULL,
  class_schedule_id INT NOT NULL,
  is_returned BOOLEAN,
  PRIMARY KEY(equipment_id, class_schedule_id),
  FOREIGN KEY(equipment_id) REFERENCES Equipment(equipment_id),
  FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);
-- Stores members' fitness progress measurements over time
CREATE TABLE Progress (
    progress_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT NOT NULL,
    check_in_date DATE DEFAULT CURRENT_DATE,
    weight_kg NUMERIC(5, 2) NOT NULL check (weight_kg > 0),
    height_cm NUMERIC(5, 2) check (height_cm > 0),
    body_fat_percentage NUMERIC(4, 2) CHECK (body_fat_percentage BETWEEN 0 AND 100),
    muscle_mass_kg NUMERIC(5, 2) CHECK (muscle_mass_kg >= 0),
    notes TEXT,
    FOREIGN KEY(member_id) REFERENCES Members(member_id)
);
-- Links trainers to scheduled classes with optional role descriptions
CREATE TABLE ClassTrainers (
    trainer_id INT NOT NULL,
    class_schedule_id INT NOT NULL,
    role_description VARCHAR(255),
    PRIMARY KEY(trainer_id, class_schedule_id),
    FOREIGN KEY(trainer_id) REFERENCES Trainers(trainer_id),
    FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);
-- Defines equipment required for specific scheduled classes
CREATE TABLE ClassEquipment (
    equipment_id INT NOT NULL,
    class_schedule_id INT NOT NULL,
    quantity_required INT DEFAULT 1,
    PRIMARY KEY(equipment_id, class_schedule_id),
    FOREIGN KEY(equipment_id) REFERENCES Equipment(equipment_id),
    FOREIGN KEY(class_schedule_id) REFERENCES ClassSchedule(class_schedule_id)
);
-- Stores trainer professional specializations and expertise areas
CREATE TABLE TrainersSpecializations(
  specialization_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id int REFERENCES Trainers(trainer_id),
  specialization_name VARCHAR(30) not null
);
-- Stores members' fitness goals, deadlines, and achievement status
CREATE TABLE FitnessGoals (
  goal_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id int REFERENCES Members(member_id),
  goal_description VARCHAR(100),
  target_date DATE,
  achievement_date DATE,
  is_achieved BOOLEAN DEFAULT FALSE
);
-- Stores personal training sessions booked between members and trainers
CREATE TABLE PersonalTraining (
  training_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id int REFERENCES Members(member_id),
  trainer_id int REFERENCES Trainers(trainer_id),
  training_date timestamp not null, 
  duration_minutes int CHECK (duration_minutes > 0)
);

CREATE INDEX idx_members_membership_id ON members(membership_id);
create index idx_attendance_member_id ON attendance(member_id);
create index idx_attendance_schedule_id ON attendance(class_schedule_id);
create index idx_progress_member_id ON progress(member_id);
create index idx_personaltraining_member_id ON personaltraining(member_id);
create index idx_personaltraining_trainer_id ON personaltraining(trainer_id);
create index idx_classschedule_class_id ON classschedule(class_id);
create index idx_trainerspecializations_trainer_id ON trainersspecializations(trainer_id);
